development:
  cloud_name: ror-trainee
  api_key: '837359836499769'
  api_secret: 9G1bNbk52eSdUiBZJCuVbxdBs3Y
  enhance_image_tag: true
  static_file_support: false
production:
  cloud_name: ror-trainee
  api_key: '837359836499769'
  api_secret: 9G1bNbk52eSdUiBZJCuVbxdBs3Y
  enhance_image_tag: true
  static_file_support: true
test:
  cloud_name: ror-trainee
  api_key: '837359836499769'
  api_secret: 9G1bNbk52eSdUiBZJCuVbxdBs3Y
  enhance_image_tag: true
  static_file_support: false