


default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: localhost
  # host: 172.16.16.242

development:
  <<: *default
  database: printany_development
  username: postgres
  password: postgres

production:
  <<: *default
  database: printany_development
  username: postgres
  password: postgres
  #username: <%#= Rails.application.credentials.production[:DATABASE_USER] %>
  #password: <%#= Rails.application.credentials.production[:DATABASE_PASSWORD] %>
